name: flat_icons_flutter
description: A new Flutter package. A set of icons from the flat icons pack included as Flutter Icons. All the essential icons which is frequently used by developers from the FlatIcon.
version: 1.0.2
author: Duncan Adjei <duncanadjei@gmail.com>
homepage: https://github.com/duncwillz/flat_icons_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
   fonts:
     - family: FlatIcons
       fonts:
         - asset: lib/fonts/Flaticon.ttf
           weight: 400
     - family: FlatIconsArrows
       fonts:
         - asset: lib/fonts/FlaticonArrows.ttf
           weight: 400
     - family: FlatIconsSocial
       fonts:
         - asset: lib/fonts/FlaticonSocial.ttf
           weight: 400      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
